run:
  timeout: 5m

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
    enable-all: true

linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - golint
    - gosimple
    - govet
    - ineffassign
    - structcheck
    - unconvert
    - unused
    - varcheck
    - errcheck
    - whitespace
    - wsl
    - godox

linters-settings:
  errcheck:
    exclude: errcheck.txt
  wsl:
    # Allow declarations (var) to be cuddled.
    allow-cuddle-declarations: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

